# Specify the base image
FROM node:18-alpine

# Set the working directory in the Docker image
WORKDIR /backend

# Copy the application files to the working directory
COPY ./backend .

# Export port 3000
EXPOSE 3000

# Run the application
CMD ["node", "app.js"]